server:
  port: 7000
wiremock:
  server:
    port: 8081
spring:
  application:
    name: github-explorer-backend
springdoc:
  swagger-ui:
    enabled: true
app:
  github:
    api:
      base-url: https://api.github.com